[package]
name = "cpu-count"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]
[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = { version = "2",default-features = true}

[build-dependencies]
napi-build = "1"
