[package]
name = "cpu-count"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
