version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  ignore:
    - dependency-name: "chalk"

  open-pull-requests-limit: 99
  versioning-strategy: increase
      # Add assignees
  assignees:
    - "Izocel"
